# Generated by Django 2.1.4 on 2019-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
